version: "3.6"

networks:
  internal-network:
    name: haproxy-hello-network

services:
  ha:
    hostname: ha1
    container_name: ha1
    image: haproxy:2.4
    networks:
      - internal-network
    ports:
      - "8888:80"
    volumes:
      - "./:/usr/local/etc/haproxy:ro"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: "0"
  uno:
    hostname: Huey
    container_name: Huey
    image: flask-hello-world
    networks:
      - internal-network
    ports:
      - "8881:80"
  dos:
    hostname: Dewey
    container_name: Dewey
    image: flask-hello-world
    networks:
      - internal-network
    ports:
      - "8882:80"
  tres:
    hostname: Louie
    container_name: Louie
    image: flask-hello-world
    networks:
      - internal-network
    ports:
      - "8883:80"
