server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://observe-loki:3100/api/prom/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: varlogs
          __path__: /var/lib/docker/containers/*/*-json.log
    
# - job_name: local
#   static_configs:
#   - targets:
#      - localhost
#     labels:
#      job: varlogs
#      __path__: /var/log/*.log

